# General settings
directory: "~/Google Drive/04. Médias/00. Musicothèque/"
library: "~/Google Drive/04. Médias/00. Musicothèque/library.db"
threaded: yes
per_disc_numbering: yes

# Plugins
plugins: inline beatport discogs

# Import settings
import:
    copy: yes
    write: yes
    resume: ask
    timid: yes
    detail: yes

# Naming settings
paths:
    default: $albumartist - $album ($original_year) [$source] %if{$catalognum,[$catalognum]}/%if{$disc_layer,$disc_layer/}$track - $title

item_fields:
    disc_layer:
        return 'CD' + str(disc) if (disctotal > 1) else None

album_fields:
    source: |
        media = set([i.media.lower() for i in items])
        format = set([i.format for i in items])
        tbr = sum([i.bitrate for i in items])
        abr = tbr / len(items) / 1000
        bitdepth = sum([i.bitdepth for i in items]) // len(items)

        # Init output
        o = [f for f in format] if format else []

        # Handle bitrate categories
        for f in format:
            if f == 'FLAC':
                o.append(str(bitdepth) + 'b')

        if abr < 480 and abr >= 320:
            o.append('320')
        elif abr < 320 and abr >= 220:
            o.append('V0')
        elif abr < 215 and abr >= 170 and abr != 192:
            o.append('V2')
        elif abr == 192:
            o.append('192')
        elif abr < 170:
            o.append(str(abr))

        # Handle media aliases
        for m in media:
            if any(t in m for t in ('digital', 'file')):
                o.append('WEB')
            elif 'vinyl' in m:
                o.append('Vinyl')
            elif 'cd' in m:
                o.append('CD')
            elif m != '':
                o.append(m)

        print(o)

        return " ".join(o)

# Discogs config
discogs:
    user_token: rxYnEGXkyclyEWrvwMYUXvsjMAuHmNQbaJuqWckx
